services:
  api-gateway:
    image: api-gateway
    build:
      context: ../services/api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__IngestionDatabase=${ConnectionStrings__IngestionDatabase}
      - ConnectionStrings__Redis=${ConnectionStrings__Redis}
      - ConnectionStrings__Kafka=${ConnectionStrings__Kafka}
      - MinIO__Host=${MinIO__Host}
      - MinIO__AccessKey=${MinIO__AccessKey}
      - MinIO__SecretKey=${MinIO__SecretKey}
    ports:
      - "7000:8080"
    restart: unless-stopped
    networks:
      - sentinel-network
  ingestion:
    image: ingestion
    build:
      context: ../services/ingestion
      dockerfile: Dockerfile
    container_name: ingestion
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7001:8080"
    depends_on:
      - postgres
      - redis
      - minio
      - kafka
    restart: unless-stopped
    networks:
      - sentinel-network
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    networks:
      - sentinel-network
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - sentinel-network
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    restart: unless-stopped
    networks:
      - sentinel-network
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT//kafka:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    restart: unless-stopped
    networks:
      - sentinel-network
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - "2181:2181"
    restart: unless-stopped
    networks:
      - sentinel-network
volumes:
  postgres-data:
  redis-data:
  minio-data:
networks:
  sentinel-network:
  