services:
  api-gateway:
    image: api-gateway
    build:
      context: ../services/api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6000:8080"
    restart: unless-stopped
  ingestion:
    image: ingestion
    build:
      context: ../services/ingestion
      dockerfile: Dockerfile
    container_name: ingestion
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7000:8080"
    restart: unless-stopped
volumes:
networks:
  