graph TD
    %% Domínio principal
    A[Domínio: Monitoramento e Alertas de Eventos Naturais]

    %% Subdomínios
    A --> B[Subdomínio: Detecção e Ingestão]
    A --> C[Subdomínio: Catálogo de Riscos]
    A --> D[Subdomínio: Geoespacial]
    A --> E[Subdomínio: Avaliação de Risco]
    A --> F[Subdomínio: Orquestração de Alertas]
    A --> I[Subdomínio: Observabilidade Operacional]

    %% Bounded Contexts Detecção e Ingestão
    B --> B1[Contexto: Ingestão de fontes externas]
    B --> B2[Contexto: Normalização e validação de dados]

    %% Bounded Contexts Catálogo de Riscos
    C --> C1[Contexto: Tipos de Evento e Severidade]
    C --> C2[Contexto: Matrizes de Risco e Curvas IDF]

    %% Bounded Contexts Geoespacial
    D --> D1[Contexto: Zonas de Risco e Rotas de Evacuação]
    D --> D2[Contexto: Consulta de contexto espacial]

    %% Bounded Contexts Avaliação de Risco
    E --> E1[Contexto: Cálculo de Score]
    E --> E2[Contexto: Dados de Catálogo e Contexto Espacial]

    %% Bounded Contexts Orquestração de Alertas
    F --> F1[Contexto: Regras de Disparo]
    F --> F2[Contexto: Gestão de Janela de Alerta]

    %% Bounded Contexts Observabilidade
    I --> I1[Contexto: Telemetria e SLIs/SLOs]
    I --> I2[Contexto: Saúde das Integrações]
