graph LR
    %% Commands
    CMD1["RegistrarColetaSensor"]
    CMD2["RegistrarEventoNatural"]
    CMD3["PublicarCatalogoRisco"]
    CMD4["DispararAlerta"]

    %% Events
    EVT1["SensorEventDetected"]
    EVT2["RiskCatalogPublished"]
    EVT3["RegionIntersected"]
    EVT4["RiskUpdated"]
    EVT5["RiskEvaluated"]
    EVT6["HighRiskDetected"]
    EVT7["AlertTriggered"]

    %% Serviços
    IS["ingestion-service"]
    GS["geospatial-service"]
    RCS["risk-catalog-service"]
    RES["risk-evaluation-service"]
    AO["alert-orchestrator"]

    %% Fluxo de Commands
    CMD1 --> IS
    CMD2 --> IS
    CMD3 --> RCS
    CMD4 --> AO

    %% Fluxo de Events
    IS --> EVT1
    EVT1 --> GS
    EVT1 --> RES
    RCS --> EVT2
    EVT2 --> RES
    GS --> EVT3
    RES --> EVT4
    RES --> EVT5
    RES --> EVT6
    EVT3 --> AO
    EVT4 --> AO
    EVT5 --> AO
    EVT6 --> AO
    AO --> EVT7
